ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER CARD IDENTIFIED BY card123';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION, RESOURCE TO CARD;
GRANT UNLIMITED TABLESPACE TO CARD;

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER STOCK IDENTIFIED BY stock123';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION, RESOURCE TO STOCK;
GRANT UNLIMITED TABLESPACE TO STOCK;

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER TRANS IDENTIFIED BY trans123';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION, RESOURCE TO TRANS;
GRANT UNLIMITED TABLESPACE TO TRANS;